### PR TITLE
Convert buildscript to use RetroFuturaGradle

### PR DESCRIPTION
**Pull request by ALongStringOfNumbers**
Converts away from Forge Gradle, which is broken some times and slow, to RetroFuturaGradle.

I didn't know what exactly to do about the travis publishing, so I copied the implementation from CEu, which uses GHA (I also copied some GHA workflows). The deployment work in the buildscript still needs to be further refined though.

### CODE REVIEW

**Comment by NotMyWing** [comment]
Replaced the previous implementation with @DStrand1's concise [buildscript](https://github.com/GregTechCEu/Buildscripts). Please feel free to take a look and point out any significant issues with the current one, if I made any mistakes porting the buildscript over.

However, I still need to add GHA CurseForge deployment actions, but I'm working on resolving that soon.

**Comment by NotMyWing** [comment]
Ready for review.
CC: @ALongStringOfNumbers, @Exaxxion, @DStrand1

**Comment by DStrand1** [comment]
The two files in the `spotless/` directory are unneeded, as spotless formatting is not being used on this repo. And if it is in the future, they can be pulled automatically from the Buildscripts repo instead of needing to be held locally. Otherwise LGTM

**Comment by NotMyWing** [comment]
image

CC: @DStrand1 @ALongStringOfNumbers @Exaxxion

**Review by Exaxxion — APPROVED** [review]

**Review by Exaxxion — APPROVED** [review]

**Pull request merged**
